[2022-09-26T02:55:54.836+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: perfinasa.colector scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2022-09-26T02:55:54.909+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: perfinasa.colector scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2022-09-26T02:55:54.910+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T02:55:54.910+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-26T02:55:54.911+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T02:55:55.022+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-08-11 00:00:00+00:00
[2022-09-26T02:55:55.039+0000] {standard_task_runner.py:54} INFO - Started process 1762 to run task
[2022-09-26T02:55:55.071+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'perfinasa', 'colector', 'scheduled__2022-08-11T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpuaaetsyt']
[2022-09-26T02:55:55.074+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask colector
[2022-09-26T02:55:55.107+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T02:56:00.430+0000] {task_command.py:384} INFO - Running <TaskInstance: perfinasa.colector scheduled__2022-08-11T00:00:00+00:00 [running]> on host 8600278d5a66
[2022-09-26T02:56:00.895+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=perfinasa
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-11T00:00:00+00:00
[2022-09-26T02:56:00.904+0000] {tasks.py:43} INFO - Defining DEC to export information
[2022-09-26T02:56:00.932+0000] {tasks.py:349} INFO - Reading prep dataframe
[2022-09-26T02:56:01.029+0000] {tasks.py:151} INFO - Instantiating the Browser with the requested settings
[2022-09-26T02:56:01.041+0000] {tasks.py:156} INFO - Browser configured
[2022-09-26T02:56:01.042+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-09-26T02:56:01.452+0000] {logger.py:11} INFO - Get LATEST geckodriver version for 102.3 firefox
[2022-09-26T02:56:01.455+0000] {logger.py:11} INFO - GH_TOKEN will be used to perform requests
[2022-09-26T02:56:02.543+0000] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/geckodriver/linux64/0.31/geckodriver] found in cache
[2022-09-26T02:56:09.380+0000] {tasks.py:279} INFO - Removing nan URL values
[2022-09-26T02:56:09.411+0000] {tasks.py:280} INFO - Requested prices before: 28
[2022-09-26T02:56:09.446+0000] {tasks.py:285} INFO - Requested prices after: 21
[2022-09-26T02:56:09.446+0000] {distinct.py:27} INFO - Add size specifications to dataframe
[2022-09-26T02:56:09.452+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 401, in colector
    date=date,
  File "/opt/airflow/dags/tasks.py", line 419, in conditional_distincter
    config=config,
  File "/opt/airflow/dags/distinct.py", line 30, in __init__
    pd.read_csv("src/resources/size.csv", sep=";", dtype=str),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'src/resources/size.csv'
[2022-09-26T02:56:09.507+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=perfinasa, task_id=colector, execution_date=20220811T000000, start_date=20220926T025554, end_date=20220926T025609
[2022-09-26T02:56:09.540+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task colector ([Errno 2] No such file or directory: 'src/resources/size.csv'; 1762)
[2022-09-26T02:56:09.599+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T02:56:09.645+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
