[2022-09-26T01:40:11.032+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T01:40:11.040+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T01:40:11.040+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T01:40:11.040+0000] {taskinstance.py:1363} INFO - Starting attempt 8 of 8
[2022-09-26T01:40:11.041+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T01:40:11.052+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): carga_creation> on 2022-09-25 00:00:00+00:00
[2022-09-26T01:40:11.055+0000] {standard_task_runner.py:54} INFO - Started process 2835 to run task
[2022-09-26T01:40:11.057+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'carga_creation', 'scheduled__2022-09-25T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp40f1ks7b']
[2022-09-26T01:40:11.058+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask carga_creation
[2022-09-26T01:40:11.059+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T01:40:11.449+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [running]> on host 4df58d125c59
[2022-09-26T01:40:11.509+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=carga_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-25T00:00:00+00:00
[2022-09-26T01:40:11.510+0000] {tasks.py:523} INFO - Reading results from collect dataframe
[2022-09-26T01:40:11.515+0000] {tasks.py:43} INFO - Defining DEC to export information
[2022-09-26T01:40:11.519+0000] {tasks.py:528} INFO - Renaming columns
[2022-09-26T01:40:11.520+0000] {tasks.py:531} INFO - Creating column with print information
[2022-09-26T01:40:11.522+0000] {tasks.py:542} INFO - Fill nan on dataset
[2022-09-26T01:40:11.524+0000] {tasks.py:545} INFO - Adapting price to the Carga file
[2022-09-26T01:40:11.526+0000] {tasks.py:446} INFO - Carga being prepared for expected data: 30/09/2022
[2022-09-26T01:40:11.526+0000] {tasks.py:551} INFO - Filling null values
[2022-09-26T01:40:11.527+0000] {tasks.py:480} INFO - Naming the price null values
[2022-09-26T01:40:11.527+0000] {tasks.py:483} INFO - Fill Sinonimous column
[2022-09-26T01:40:11.528+0000] {tasks.py:490} INFO - Creating a justification for null prices
[2022-09-26T01:40:11.528+0000] {tasks.py:497} INFO - Fill URL column
[2022-09-26T01:40:11.529+0000] {tasks.py:504} INFO - Fill date column
[2022-09-26T01:40:11.530+0000] {tasks.py:554} INFO - Fill regions column
[2022-09-26T01:40:11.532+0000] {tasks.py:560} INFO - Reordering column
[2022-09-26T01:40:11.532+0000] {tasks.py:562} INFO - Finishing the process
[2022-09-26T01:40:11.532+0000] {tasks.py:563} INFO - Total prices: 15
[2022-09-26T01:40:11.538+0000] {warnings.py:110} WARNING - /opt/***/dags/tasks.py:573: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  ).to_excel(f"{EXPORT}")

[2022-09-26T01:40:11.549+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 573, in carga_creation
    ).to_excel(f"{EXPORT}")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_xlwt.py", line 51, in __init__
    engine_kwargs=engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 926, in __init__
    path, mode, storage_options=storage_options, is_text=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/./data_output/coleta_2022/coleta_September/coleta_3_dec/saida_2022_09_26/carga_ENCASA_26_09_2022.xls'
[2022-09-26T01:40:11.557+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=carga_creation, execution_date=20220925T000000, start_date=20220926T014011, end_date=20220926T014011
[2022-09-26T01:40:11.566+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task carga_creation ([Errno 2] No such file or directory: '/./data_output/coleta_2022/coleta_September/coleta_3_dec/saida_2022_09_26/carga_ENCASA_26_09_2022.xls'; 2835)
[2022-09-26T01:40:11.590+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T01:40:11.605+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
