[2022-09-26T00:43:28.130+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T00:43:28.138+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T00:43:28.138+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T00:43:28.139+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 4
[2022-09-26T00:43:28.139+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T00:43:28.150+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): carga_creation> on 2022-09-25 00:00:00+00:00
[2022-09-26T00:43:28.155+0000] {standard_task_runner.py:54} INFO - Started process 2120 to run task
[2022-09-26T00:43:28.156+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'carga_creation', 'scheduled__2022-09-25T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcyxz5xim']
[2022-09-26T00:43:28.157+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask carga_creation
[2022-09-26T00:43:28.157+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T00:43:28.549+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [running]> on host c726b2151513
[2022-09-26T00:43:28.608+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=carga_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-25T00:00:00+00:00
[2022-09-26T00:43:28.609+0000] {tasks.py:521} INFO - Reading results from collect dataframe
[2022-09-26T00:43:28.612+0000] {tasks.py:43} INFO - Defining DEC to export information
[2022-09-26T00:43:28.617+0000] {tasks.py:526} INFO - Renaming columns
[2022-09-26T00:43:28.618+0000] {tasks.py:529} INFO - Creating column with print information
[2022-09-26T00:43:28.620+0000] {tasks.py:540} INFO - Fill nan on dataset
[2022-09-26T00:43:28.622+0000] {tasks.py:543} INFO - Adapting price to the Carga file
[2022-09-26T00:43:28.624+0000] {tasks.py:444} INFO - Carga being prepared for expected data: 30/09/2022
[2022-09-26T00:43:28.625+0000] {tasks.py:549} INFO - Filling null values
[2022-09-26T00:43:28.625+0000] {tasks.py:478} INFO - Naming the price null values
[2022-09-26T00:43:28.626+0000] {tasks.py:481} INFO - Fill Sinonimous column
[2022-09-26T00:43:28.627+0000] {tasks.py:488} INFO - Creating a justification for null prices
[2022-09-26T00:43:28.627+0000] {tasks.py:495} INFO - Fill URL column
[2022-09-26T00:43:28.628+0000] {tasks.py:502} INFO - Fill date column
[2022-09-26T00:43:28.628+0000] {tasks.py:552} INFO - Fill regions column
[2022-09-26T00:43:28.630+0000] {tasks.py:558} INFO - Reordering column
[2022-09-26T00:43:28.630+0000] {tasks.py:560} INFO - Finishing the process
[2022-09-26T00:43:28.630+0000] {tasks.py:561} INFO - Total prices: 15
[2022-09-26T00:43:28.637+0000] {warnings.py:110} WARNING - /opt/***/dags/tasks.py:571: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  ).to_excel(f"{DEFAULT_PATH}{EXPORT}")

[2022-09-26T00:43:28.638+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 571, in carga_creation
    ).to_excel(f"{DEFAULT_PATH}{EXPORT}")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_xlwt.py", line 39, in __init__
    import xlwt
ModuleNotFoundError: No module named 'xlwt'
[2022-09-26T00:43:28.647+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=carga_creation, execution_date=20220925T000000, start_date=20220926T004328, end_date=20220926T004328
[2022-09-26T00:43:28.657+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task carga_creation (No module named 'xlwt'; 2120)
[2022-09-26T00:43:28.690+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T00:43:28.707+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
